version: '3'

tasks:
  all:
    cmds:
      - task: cleanup
      - task: build
      - task: package
      - task: adb
    silent: true

  build:
    cmds:
      - rm -rf build
      - mkdir -p build
      - mkdir -p build/lib
      - docker buildx build --platform=linux/arm64 -t retro-console-arm64 -f Dockerfile .
    silent: true

  download-romnibus-dev:
    cmds:
      - mkdir -p resources
      - curl -o resources/ROMnibus.sqlite.zip -L https://github.com/UncleJunVIP/ROMnibus/releases/latest/download/ROMnibus.sqlite.zip
      - cd resources && unzip ROMnibus.sqlite.zip && rm ROMnibus.sqlite.zip

  package:
    cmds:
      - docker create --name extract retro-console-arm64
      - docker cp extract:/build/game-manager build/game-manager
      - docker cp extract:/usr/lib/aarch64-linux-gnu/libSDL2_gfx-1.0.so.0.0.2 build/lib/libSDL2_gfx-1.0.so.0
      - rm -rf "build/Game Manager.pak" || true
      - mkdir -p "build/Game Manager.pak"
      - mkdir -p "build/Game Manager.pak/resources/lib"
      - curl -o "build/Game Manager.pak/resources/ROMnibus.sqlite.zip" -L https://github.com/UncleJunVIP/ROMnibus/releases/latest/download/ROMnibus.sqlite.zip
      - cd "build/Game Manager.pak/resources" && unzip ROMnibus.sqlite.zip && rm ROMnibus.sqlite.zip
      - cp build/game-manager launch.sh README.md LICENSE pak.json "build/Game Manager.pak"
      - cp -R build/lib "build/Game Manager.pak/resources"
    silent: true

  cleanup:
    cmds:
      - docker rm extract || true
    silent: true

  adb:
    cmds:
      - adb shell rm -rf "/mnt/SDCARD/Tools/tg5040/Game Manager.pak" || true
      - adb push "build/Game Manager.pak" /mnt/SDCARD/Tools/tg5040
      - adb push config.yml "/mnt/SDCARD/Tools/tg5040/Game Manager.pak"
      - say Finished deploying Game Manager!
    silent: true

  kill:
    cmds:
      - sshpass -p 'tina' ssh root@192.168.1.210 "kill  \$(pidof dlv)" > /dev/null 2>&1 || true
      - sshpass -p 'tina' ssh root@192.168.1.210 "kill  \$(pidof game-manager)" > /dev/null 2>&1 || true
    silent: true

  debug:
    cmds:
      - sshpass -p 'tina' ssh root@192.168.1.210 "sh -c '/mnt/SDCARD/Developer/bin/dlv attach --headless --listen=:2345 --api-version=2 --accept-multiclient \$(pidof game-manager)'" > /dev/null &
      - printf "Press any key to quit debugging...\n"
      - read
      - task: kill
    silent: true
