name: Package Game Manager

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Build
        run: CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC="zig cc -target aarch64-linux" CXX="zig c++ -target aarch64-linux" go build -o game-manager --tags extended .

      - name: Build Package Folder
        run: |
          mkdir Mortar.pak
          cp -R game-manager launch.sh README.md LICENSE resources/config.json resources/bin resources/certs resources/data "Game Manager.pak"

      - uses: actions/upload-artifact@v4
        with:
          name: 'Game Manager.pak'
          path: 'Game Manager.pak'
          if-no-files-found: error
          retention-days: 3
          overwrite: true
